### ISSUE TITLE
help

### ISSUE THREAD

**Issue by EricSmith16** [josh33901/F1Cheat#2]
So, i compiled F1-SDK to static lib.
but how to use F1Cheat ? I dont see solution file :1st_place_medal:

**Comment by KaylinOwO** [comment]
install a brain

**Comment by KaylinOwO** [comment]
You call me stupid yet can't figure out how to compile a cheat off of GitHub, a bit ironic there, my dude.

**Comment by josh33901** [comment]
F1Cheat uses premake so just `premake5.exe vs2017` and it will create a solution file.
